require('fzf-lua').setup({'telescope'})

vim.keymap.set('n', '<c-p>', ':FzfLua git_files<CR>')
vim.keymap.set('n', '<leader>f', ':FzfLua files<CR>')
vim.keymap.set('n', '<leader>g', ':FzfLua grep<CR>')
vim.keymap.set('n', '<leader>;', ':FzfLua buffers<CR>')
vim.keymap.set('n', '<leader>a', ':FzfLua grep_cword<CR>')
vim.keymap.set('n', '<leader>v', ':FzfLua grep_visual<CR>')
vim.keymap.set('n', '<leader>r', ':FzfLua grep_project<CR>')
vim.keymap.set('n', '<leader>l', ':FzfLua lines<CR>')
vim.keymap.set('n', '<leader>/', ':FzfLua blines<CR>')
vim.keymap.set('n', '<leader>.', ':FzfLua quickfix<CR>')
vim.keymap.set('n', '<leader>m', ':FzfLua marks<CR>')
vim.keymap.set('n', '<leader>c', ':FzfLua commands<CR>')
